#!/usr/bin/env python3
from __future__ import annotations

import json
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DNS_DIR = ROOT / "dns"
TOOL_DIR = Path(__file__).resolve().parent
UA = "proxy-rules/ai-fail-closed"
MIHOMO_DNS = "127.0.0.1:1053"

META_BASE = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite"
UPSTREAMS = {
    "openai": f"{META_BASE}/openai.yaml",
    "anthropic": f"{META_BASE}/anthropic.yaml",
    "gemini": f"{META_BASE}/google-gemini.yaml",
}

EXPECTED = {
    "openai": {"chatgpt.com", "openai.com"},
    "anthropic": {"anthropic.com", "claude.ai"},
    "gemini": {"gemini.google.com", "gemini.google"},
}


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as response:
        return response.read().decode("utf-8")


def norm(domain: str) -> str:
    domain = domain.strip().lower().rstrip(".")
    if domain.startswith("+."):
        domain = domain[2:]
    return domain


def parse_meta_yaml(text: str) -> set[str]:
    domains: set[str] = set()
    for raw in text.splitlines():
        line = raw.strip()
        if not line.startswith("- "):
            continue
        value = norm(line[2:])
        if value:
            domains.add(value)
    return domains


def parse_clash_rules(text: str) -> set[str]:
    domains: set[str] = set()
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [item.strip() for item in line.split(",")]
        if len(parts) < 2:
            continue
        rule_type, value = parts[0].upper(), norm(parts[1])
        if rule_type in {"DOMAIN", "DOMAIN-SUFFIX"} and value:
            domains.add(value)
    return domains


def agh_fallback(domains: set[str]) -> str:
    ordered = sorted(domains)
    return f"[/{'/'.join(ordered)}/]{MIHOMO_DNS}"


def main() -> None:
    DNS_DIR.mkdir(parents=True, exist_ok=True)
    TOOL_DIR.mkdir(parents=True, exist_ok=True)

    groups: dict[str, set[str]] = {}
    for name, url in UPSTREAMS.items():
        domains = parse_meta_yaml(fetch(url))
        missing = EXPECTED[name] - domains
        if missing:
            raise RuntimeError(
                f"{name} upstream lost expected domains: {', '.join(sorted(missing))}"
            )
        groups[name] = domains

    openrouter_path = ROOT / "rules" / "openrouter.list"
    openrouter = parse_clash_rules(openrouter_path.read_text(encoding="utf-8"))
    if "openrouter.ai" not in openrouter:
        raise RuntimeError("openrouter.ai disappeared from rules/openrouter.list; aborting.")
    groups["openrouter"] = openrouter

    lines = [
        "# AI fail-closed fallback rules for AdGuard Home",
        "# Generated automatically; do not edit this file by hand.",
        "# Intended use: prepend these entries to AdGuard Home fallback_dns.",
        f"# Matching AI domains are sent only to Mihomo DNS at {MIHOMO_DNS}.",
        "# If both MosDNS and Mihomo DNS are unavailable, resolution should fail instead of falling through to public DNS.",
        "# Default public fallback DNS entries must remain after these domain-specific entries for non-AI domains.",
        "",
    ]

    for name in ("openai", "anthropic", "gemini", "openrouter"):
        lines.append(f"# {name}")
        lines.append(agh_fallback(groups[name]))
        lines.append("")

    output = DNS_DIR / "ai-fail-closed-adguardhome.generated.txt"
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    metadata = {
        "target": "adguardhome-fallback-dns",
        "mihomo_dns": MIHOMO_DNS,
        "sources": {
            **UPSTREAMS,
            "openrouter": "rules/openrouter.list",
        },
        "groups": {name: len(domains) for name, domains in groups.items()},
        "total_unique_domains": len(set().union(*groups.values())),
    }
    (TOOL_DIR / "metadata.generated.json").write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(metadata, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
